// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions chưa được cấu hình cho Linux. '
          'Bạn có thể cấu hình lại bằng cách chạy FlutterFire CLI.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions chưa hỗ trợ nền tảng này.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeFbZamIPGmRD7noFivkvFivjCbIZBNiQ',
    appId: '1:412875888909:web:bab599e0ad1aae5f4f7844',
    messagingSenderId: '412875888909',
    projectId: 'food-order-ebbb9',
    authDomain: 'food-order-ebbb9.firebaseapp.com',
    storageBucket: 'food-order-ebbb9.firebasestorage.app',
    measurementId: 'G-QW60K6YFJR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLv5r1C-sMJ25vmEHVyx7YAfoFzlWvdY8',
    appId: '1:412875888909:android:c8a4f50bb25c400e4f7844',
    messagingSenderId: '412875888909',
    projectId: 'food-order-ebbb9',
    storageBucket: 'food-order-ebbb9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhK-e3pc94_PG1g7AiYtBTaxZ4fHggXH0',
    appId: '1:412875888909:ios:807b67efeb60fc9a4f7844',
    messagingSenderId: '412875888909',
    projectId: 'food-order-ebbb9',
    storageBucket: 'food-order-ebbb9.firebasestorage.app',
    iosBundleId: 'com.example.foodOrder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhK-e3pc94_PG1g7AiYtBTaxZ4fHggXH0',
    appId: '1:412875888909:ios:807b67efeb60fc9a4f7844',
    messagingSenderId: '412875888909',
    projectId: 'food-order-ebbb9',
    storageBucket: 'food-order-ebbb9.firebasestorage.app',
    iosBundleId: 'com.example.foodOrder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeFbZamIPGmRD7noFivkvFivjCbIZBNiQ',
    appId: '1:412875888909:web:6cfbb5ab804b5f384f7844',
    messagingSenderId: '412875888909',
    projectId: 'food-order-ebbb9',
    authDomain: 'food-order-ebbb9.firebaseapp.com',
    storageBucket: 'food-order-ebbb9.firebasestorage.app',
    measurementId: 'G-43GNZM1ZF1',
  );
}
